name: 'Add new issue to Project'

on:
  issues:
    types:
      - opened

jobs:
  add_to_project:
    name: Add issue to project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Add issue to Project
        uses: actions/add-to-project@main
        with:  
          project: https://github.com/users/jefersonqui-dev/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}
